### ISSUE TITLE
페이지 전체에 적용 되는 네비게이션 바 추가

### ISSUE THREAD

**Issue by Pavel-Dmr** [Pavel-Dmr/GreenDining#18]
position-fixed 로 된 네비게이션 바을 추가해서 페이지 맨 위에 위치 해 있지 않더라도
로그인,장바구니,배송,최근 본 상품 등에 접근 가능 하도록 디자인 한다.

- [x] 네비게이션 바 추가

**Comment by dlsgur8431** [comment]
해당 작업 완료 했으니 이슈 종료합니다.
